### PR TITLE
Xunit 2.0 support

### PR DESCRIPTION
**Pull request by jamesrcounts**
I believe this will address the issues in #112.  If someone could test/review and let me know if the encounter any issues...

### CODE REVIEW

**Comment by hatboyzero** [comment]
Yup, just tested it.  It works as expected for theories now.

**Comment by jamesrcounts** [comment]
If anyone else wants to test this branch, there is a feed here which contains a customized nuget package: https://www.myget.org/F/approvalfork/

**Comment by hatboyzero** [comment]
I've since been able to reproduce desired results in four separate projects that utilize theories.  It's rock solid as far as I'm concerned.

**Comment by niemyjski** [comment]
Looks good, ship it.

**Comment by niemyjski** [comment]
ty :)

**Comment by niemyjski** [comment]
Any idea when this will be on nuget?

Thanks
-Blake Niemyjski

**Comment by niemyjski** [comment]
Any ideas on a release date for the nuget package?

**Comment by jamesrcounts** [comment]
Maybe the CI build can hold you over until there is a new nuget release?

This is the official source of the pre-release ApprovalTests packages:
https://www.myget.org/gallery/approvaltests

If @isidore was to log in right now and do a release, you would get the exact same code as is currently published on the myget feed.

**Comment by niemyjski** [comment]
I'm getting an error when I try to view that feed.

**Comment by jamesrcounts** [comment]
Ok I just checked the gallery page incognito and I could see it fine.  So I'm not sure I can help with that.  

The actual nuget feed URL is https://www.myget.org/F/approvaltests/

Can you add that as a package source in Visual Studio?  The basic process will be similar to this: http://ihadthisideaonce.com/2012/03/09/install-nuget-packages-from-the-cache/

If you are able to add it, be sure to select "Include Prerelease" when browsing in the nuget GUI, then the CI build should show up.

**Comment by niemyjski** [comment]
I'll try that, yeah sometimes myget has issues.

On 4/8/15, Jim Counts <notifications@github.com> wrote:
> Ok I just checked the gallery page incognito and I could see it fine.  So
> I'm not sure I can help with that.
>
> The actual nuget feed URL is https://www.myget.org/F/approvaltests/
>
> Can you add that as a package source in Visual Studio?  The basic process
> will be similar to this:
> http://ihadthisideaonce.com/2012/03/09/install-nuget-packages-from-the-cache/
>
> If you are able to add it, be sure to select "Include Prerelease" when
> browsing in the nuget GUI, then the CI build should show up.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/approvals/ApprovalTests.Net/pull/113#issuecomment-91001392


-- 
Thanks
-Blake Niemyjski

**Pull request merged**
