### PR TITLE
Add support for TortoiseGitMerge as Reporter

### PR DESCRIPTION
**Pull request by 304NotModified**
As TortoiseMerge isn't working when only installed TortioseGit. 

Tested locally.

### CODE REVIEW

**Comment by 304NotModified** [comment]
No AppVeyor here (free build server)? Should I help implement it?

**Comment by 304NotModified** [comment]
polite bump

**Comment by jamesrcounts** [comment]
LGTM

**Comment by 304NotModified** [comment]
Could you tell which version this will be released?

**Pull request merged**
