### PR TITLE
Extend doc about diff tool order with info about DiffEngine_ToolOrder

### PR DESCRIPTION
**Pull request by cezarypiatek**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@cezarypiatek you should probably move to use https://github.com/VerifyTests/Verify

**Comment by cezarypiatek** [comment]
@SimonCropp  you are probably right but I need more time to understand the difference between those two libraries.  I also have several projects under development that are actively using ApprovalTests and a set of extensions that address my needs and feedback from the QA  with whom I have the opportunity to work.

**Comment by cezarypiatek** [comment]
Why my changes were reverted by @actions-user ?

https://github.com/approvals/ApprovalTests.Net/commit/9d578e53fa7f082736de07922f77814722f308a5#diff-41a8cbfa8dd302bbffae9154741637a5766fc31465378cb3513a0441bcb3b18d

**Comment by SimonCropp** [comment]
fix it

**Pull request merged**
