### PR TITLE
Added support for Beyond Compare 4 to BeyondCompareReporter

### PR DESCRIPTION
**Pull request by james-world**
Updated the `BeyondCompareRerporter` so that it looks for version 4 as well as version 3.

### CODE REVIEW

**Comment by CraigRichards** [comment]
This would be a great help where i am currently working. Any idea of when this might be committed? I would like to demo this framework to my colleagues.

**Comment by jamesrcounts** [comment]
Tested this PR.  It throws an exception on a machine *without* Beyond Compare on it.  See below.  It needs to handle the case where machines do not have the reporter on it (like a build server).  

Also please add tests that cover and verify the changes you are making.

It seems like a good idea, just needs some more work.


    System.TypeInitializationExceptionThe type initializer for 'ApprovalTests.Reporters.DiffReporter' threw an exception.
    Exception doesn't have a stacktrace
    System.TypeInitializationExceptionThe type initializer for 'ApprovalTests.Reporters.BeyondCompareReporter' threw an exception.
       at ApprovalTests.Reporters.DiffReporter..ctor() in DiffReporter.cs: line 7
       at ApprovalTests.Reporters.DiffReporter..cctor() in DiffReporter.cs: line 5
    System.NullReferenceExceptionIllegal arguments for BeyondCompareReporter (diffProgam, argumentsFormat, diffProgramNotFoundMessage)
    Recieved BeyondCompareReporter (, "{0}" "{1}", Could not find BeyondCompare at , please install it)
       at ApprovalTests.Reporters.GenericDiffReporter..ctor(String diffProgram, String argumentsFormat, String diffProgramNotFoundMessage, Func`1 allowedFileTypes) in GenericDiffReporter.cs: line 105
       at ApprovalTests.Reporters.BeyondCompareReporter..ctor() in BeyondCompareReporter.cs: line 12
       at ApprovalTests.Reporters.BeyondCompareReporter..cctor() in BeyondCompareReporter.cs: line 10

**Comment by isidore** [comment]
This is not the right pattern to solve this problem. It should use a chain of responsibility pattern. Solved in 9dd395e00ee2a9fddc097ce3dfbf0ab6becd49a3

**Comment by james-world** [comment]
Fair enough, I was trying to mimic the existing code without changing too much - that file path discovery code was a little weird. Thanks for rolling a working version in.

**Pull request closed without merging**
