### PR TITLE
Xamarin Studio/Mono support on a Mac?

### PR DESCRIPTION
**Pull request by staxmanade**
# This is a rough start for now...

## What **IS** in here

- [x] I'm using a number of pre-compiler flag `__MonoCS__` to exclude compiling certain parts of the project that we don't have support for in the Mac such as WPF, etc...
- [x] A number of directory path separator fixes

# What is known broken or room for improvement?
- [ ] We don't have clipboard support at the moment `ClipboardUtilities` can't access `Clipboard.SetText(...)` we could look into the use of `Gtk.Clipboard` as an alternative
- [ ] The unit tests are sitting about `105` passing 1 Failure and 4 Errors. I've excluded from even running a number of the tests that depend on the CassiniDevServer.
- [X] **[FIXED]** There a number of failure errors reported (as approval tests) where stack traces are used in the approval.
- [ ] Strangely the way `Araxis` diff program is named caused a funny scenario on my computer. `Araxis/Araxis Merge/Compare.exe` (due to changes in this branch) turns into a lookup for `compare` on `PATH` which on my machine resulted in `/opt/boxen/homebrew/bin/Compare` - however this `Compare` is actually ImageMagic's compare. Hmmm

# Optional future upgrades
- [x] We could get this up and running on a travis-ci? (You can look at the [pash project](https://github.com/Pash-Project/Pash/) as an example of a .net project that is setup to run across environments (both Mac/Linux/Windows).

### CODE REVIEW

**Comment by jamesrcounts** [comment]
For the stack trace variations we can use UniqueForOs https://github.com/approvals/ApprovalTests.Net/blob/2ea22b074200fa762f277974ae15cf5073fe9fb2/ApprovalTests/Namers/ApprovalResults.cs#L65

Of course, this doesn't have OSX support currently, you will have to add support in GetOSName in the same file.

Travis-ci sounds awesome, we also have a friend who offered us space on their team city server.  Either/both should be pursued as we go forward.

**Comment by staxmanade** [comment]
Hey @jamesrcounts I can try to add the `GetOSName` support, how do I tell the tests to leverage that functionality?

**Comment by jamesrcounts** [comment]
```csharp
[Test]
public void TestThatWillVaryByOs()
{
    using(ApprovalResults.UniqueForOs())
    {
         // Arrange, Act, Assert
    }
}
```

**Comment by staxmanade** [comment]
@jamesrcounts that example was helpful - thanks.

Is there a utility I should look at that trims out fully qualified paths in the output? So for this stack trace I want to remove my `/Users/jason/...` part of the path...

```
System.Exception: Exception of type 'System.Exception' was thrown.
  at ApprovalTests.Tests.ExceptionTests.<TestVerifyException> () [0x00001] in /Users/jason/code/personal/ApprovalTests.Net/ApprovalTests.Tests/ExceptionTests.cs:14 
  at ApprovalUtilities.Utilities.ExceptionUtilities.GetException (System.Action action) [0x00006] in /Users/jason/code/personal/ApprovalTests.Net/ApprovalUtilities/Utilities/ExceptionUtilities.cs:45 
```

**Comment by jamesrcounts** [comment]
StackTrace is automatically scrubbed for exceptions.  So if you add support for forward slashes here you should get the behavior you want on OSX:

https://github.com/approvals/ApprovalTests.Net/blob/2ea22b074200fa762f277974ae15cf5073fe9fb2/ApprovalTests/Utilities/StackTraceScrubber.cs#L21

**Comment by staxmanade** [comment]
Is this test passing on windows?

```
		[Test]
		public void TestClassLevel()
		{
			Assert.AreEqual(typeof(DiffReporter), Approvals.GetReporter().GetType());
		}
```

Because I don't know how it could... the assembly level attribute is set to a `TortoiseDiffReporter`.

**Comment by jamesrcounts** [comment]
I've got diff reporter
https://github.com/approvals/ApprovalTests.Net/blob/2ea22b074200fa762f277974ae15cf5073fe9fb2/ApprovalTests.Tests/Properties/AssemblyInfo.cs#L12

**Comment by staxmanade** [comment]
Ahh, I'm not seeing that. On the HEAD of master I'm seeing Tortise and here's why: 

https://github.com/approvals/ApprovalTests.Net/commit/2ec96de99fcfd40bca3c91592a40db550f327957

@isidore any thoughts?

**Comment by staxmanade** [comment]
Ok, I have `105` passing tests and `6` failures. At lest one error is because of `https://github.com/approvals/ApprovalTests.Net/commit/2ec96de99fcfd40bca3c91592a40db550f327957`. 

@jamesrcounts Could you do me a favor, check out this branch and verify that I didn't break anything on the windows side? If so, let me know an I can have another look at anything you find (unless you fix it directly).

Beyond that, we have most of `ApprovalTests.Net` working over on a mac.

**Comment by jamesrcounts** [comment]
Looks good :+1:

**Comment by staxmanade** [comment]
@jamesrcounts any reason not to merge what's here?

**Comment by jamesrcounts** [comment]
None that I see.  @isidore, any input?

**Pull request merged**
