### PR TITLE
Multi-target ApprovalTests (Utilities is also multi-target)

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@SimonCropp ApprovalTestUtilities is multi-targetted. Given the debacle with netstandard2.0 probably it is better to multi-target ApprovalTests as well

**Comment by SimonCropp** [comment]
ApprovalTestUtilities is multi-targetted since there are some utils in there that people are using in production code. which is more difficult to update. ApprovalTest targets only test code, which is easier to run on a newer runtime

What is the netstandard2.0 debacle?

**Comment by danielmarbach** [comment]
https://twitter.com/terrajobst/status/1031999730320986112?lang=de
https://twitter.com/davidfowl/status/1034105392475791361

**Comment by bording** [comment]
They also have open-source library guidance that touches on multi-targeting: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#multi-targeting

I'd say that the "consider" language is too weak, especially considering the tweets @danielmarbach linked to.

**Comment by SimonCropp** [comment]
lets see if we can get some official stance https://github.com/dotnet/docs/pull/10448

**Comment by SimonCropp** [comment]
@isidore the guidance got updated https://github.com/dotnet/docs/pull/10504/files

i have no opinion on this since it doesn effect me

@bording @danielmarbach it was also my understanding that you are moving off approvaltests?

**Comment by bording** [comment]
Given the guidance, I think generally you either need to have a `net461` target along with a `netstandard2.0 target` like this PR adds, or you need to ensure that your `netstandard2.0` target will only be used on `net472` or higher though MSBuild.

>  it was also my understanding that you are moving off approvaltests?

Yes, we have moved our repos away from ApprovalTests.Net.

**Comment by SimonCropp** [comment]
@bording the advice is that 

> For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

Not that "those project", not "those nugets"

I understand your stance, but it seem unreasonable to expect FOSS projects to go to the extra effort of enforcing this when MS libs (eg asp core, and EF) do not take this approach.

If MS wants to enforce "nugets targeting only netstandard2 can only be referenced by net472" then that is a thing they should enforce at the nuget level. The effort should not be pushed on to every individual OSS project to duplicate that effort.

**Comment by bording** [comment]
The larger point I was trying to make in my previous comment is that, as a package author, if you want to support `net461` - `net471` with your package, then just providing a `netstandard2.0` target doesn't really work well to do that. Instead, you should also provide a `net461` target in the package.

If you're fine with saying `net472`+ is all you support, then just shipping `netstandard2.0` does work fine, except there's no real way for consumers of your package to know about that due to the way NuGet currently works. That's where I think you could add MSBuild enforcement in your package, so consumers will at least get something at runtime telling them you don't support < `net472`.

Maybe it would be a good idea to come up with a `net472`-only enforcement package that packages could take as a dependency, and then each package author wouldn't need to write it themselves?

> If MS wants to enforce "nugets targeting only netstandard2 can only be referenced by net472" then that is a thing they should enforce at the nuget level. The effort should not be pushed on to every individual OSS project to duplicate that effort.

I 100% agree that Microsoft should be changing something here to make it easy for packages to opt-in to some `net472`-only enforcement without needing to do it manually.

I've been wanting to open a NuGet/Home issue about this for a while, but I haven't had the time to get to to it yet.

**Comment by isidore** [comment]
Hope this solves your problems, thanks!

**Pull request merged**
